//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heima8.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Instance
    {
        public WF_Instance()
        {
            this.DelFlag = 0;
            this.FileInfo = new HashSet<FileInfo>();
            this.WF_Step = new HashSet<WF_Step>();
        }
    
        public int ID { get; set; }
        public string InstanceName { get; set; }
        public int StartBy { get; set; }
        public System.DateTime StartTime { get; set; }
        public short Level { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public short DelFlag { get; set; }
        public string FilePath { get; set; }
        public System.Guid WFInstanceId { get; set; }
        public int WF_TempID { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<FileInfo> FileInfo { get; set; }
        public virtual WF_Temp WF_Temp { get; set; }
        public virtual ICollection<WF_Step> WF_Step { get; set; }
    }
}
