//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heima8.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Temp
    {
        public WF_Temp()
        {
            this.DelFlag = 0;
            this.WF_Instance = new HashSet<WF_Instance>();
        }
    
        public int ID { get; set; }
        public string TepName { get; set; }
        public string Description { get; set; }
        public string TempForm { get; set; }
        public string Remark { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public string ActityType { get; set; }
    
        public virtual ICollection<WF_Instance> WF_Instance { get; set; }
    }
}
